esphome:
  name: door-sensor
  on_boot: 
    then:
      - if: 
          condition:
            - binary_sensor.is_on: door_sensor
          then:
            - light.turn_on: open_led
          else: 
            - light.turn_off: open_led

esp32:
  board: esp32dev

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: HIGH
  fast_connect: true

logger:
  level: DEBUG

ota:
  platform: esphome

api:
bluetooth_proxy:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO4  # Reed switch for door sensor
      inverted: False
      mode: INPUT_PULLUP
    name: "Door Sensor"
    id: door_sensor
    device_class: door
    on_press:
      - logger.log: "Door Opened!"
      - light.turn_on: open_led
    on_release:
      - logger.log: "Door Closed!"
      - light.turn_off: open_led

light:
  - platform: status_led
    internal: True
    id: open_led
    pin: GPIO2

sensor:
  - platform: dht
    pin: GPIO18  # DHT22 temperature/humidity sensor
    model: DHT22
    update_interval: 10s
    temperature:
      name: "Living Room Temperature"
      accuracy_decimals: 1
      id: temp_sensor
      unit_of_measurement: "°C"
    humidity:
      name: "Living Room Humidity"
      accuracy_decimals: 1
      id: humidity_sensor
      unit_of_measurement: "%"

